AWSTemplateFormatVersion: "2010-09-09" # CloudFormation 템플릿의 버전 지정
Description: topycare amplify app # 템플릿에 대한 설명

Transform:
  - AWS::Serverless-2016-10-31 # AWS SAM 변환기 사용

Parameters:
  Repository:
    Type: String
    Description: GitHub repository URL for the Amplify app
  BranchName:
    Type: String
    Default: main
    Description: The name of the branch to deploy
  EnvironmentName:
    Type: String
    Default: dev
    Description: The name of the backend environment
  BucketName:
    Type: String
    Description: S3 bucket name for the Amplify app
  LambdaArchitecture:
    Description: The instruction set architecture for the function
    Type: String
    Default: arm64
    AllowedValues:
      - x86_64
      - arm64
  FoodHandlerApiName:
    Description: Name of RestApi - food handler
    Type: String
    Default: topycare-food-handler

Resources: # AWS 리소스 정의 섹션
  S3AccessRole: # for amplify
    Type: AWS::IAM::Role
    Properties:
      RoleName: topycare-s3-access-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource:
                  - !GetAtt Bucket.Arn
                  - !Sub "${Bucket.Arn}/*"
  LambdaRole: # for lambda
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub lambda.${AWS::URLSuffix}
            Action: sts:AssumeRole
      Path: /service-role/
      ManagedPolicyArns: # https://docs.aws.amazon.com/lambda/latest/dg/security-iam-awsmanpol.html
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: AmazonS3Access # https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_s3_rw-bucket.html
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub arn:${AWS::Partition}:s3:::${BucketName}
                  - !Sub arn:${AWS::Partition}:s3:::${BucketName}/*
        - PolicyName: AWSAPIGatewayPushToCloudWatchLogs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                  - logs:GetLogEvents
                  - logs:FilterLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*"
  
  TopycareVPC: # 네트워크의 기본 단위. / 보완필요 : 태그 추가(관리 편의), DNS 지원 활성화(내부 서비스 접근 용이)
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

  TopycareSubnet: # VPC 내에서 IP 주소 범위를 나누는 논리적 구분. / 보완필요 : 가용영역 지정(고가용성(멀티 AZ)), 태그 추가(관리 편의)
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref TopycareVPC
      CidrBlock: 10.0.1.0/24

  TopycareSecurityGroup: # 인스턴스/람다의 네트워크 접근 제어. / 보완필요 : 인바운드/아웃바운드 규칙 명시(ex. VPC 내부 통신 허용)
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Lambda access to S3
      VpcId: !Ref TopycareVPC

  TopycareRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref TopycareVPC
      Tags:
        - Key: Name
          Value: topycare-route-table

  TopycareSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref TopycareSubnet
      RouteTableId: !Ref TopycareRouteTable

  GitHubAccessTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: github-token
      Description: GitHub Personal Access Token for Amplify
      # SecretString: {} // 최초 생성때만 필요. 생성 후 콘솔에서 직접 수정 후 제거.

  AmplifyApp: # Amplify 애플리케이션 리소스
    Type: AWS::Amplify::App # 리소스 타입 지정
    Properties: # 리소스의 속성 정의
      Name: topycare # Amplify 앱 이름
      Repository: !Ref Repository # 연결된 GitHub 저장소 URL
      AccessToken: !Sub "{{resolve:secretsmanager:${GitHubAccessTokenSecret}::SecretString}}"
      BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - nvm install 20
                - nvm use 20
                - npm install
            build:
              commands:
                - npm run build
          artifacts:
            baseDirectory: dist   # Vite 기본 output 디렉토리
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
      # IAMServiceRole: arn:aws:iam::${AWS::AccountId}:role/amplify-service-role # Amplify가 사용할 IAM 역할 ARN
      # EnvironmentVariables: # 앱 전체에 적용되는 환경 변수
        # - Name: _LIVE_PACKAGE # 환경 변수 이름
        #   Value: "true" # 환경 변수 값

  AmplifyBranch: # Amplify 앱의 브랜치 리소스
    Type: AWS::Amplify::Branch # 리소스 타입 지정
    Properties: # 리소스의 속성 정의
      AppId: !GetAtt AmplifyApp.AppId # 연결할 Amplify 앱의 ID
      BranchName: !Ref BranchName # 브랜치 이름
      Stage: DEVELOPMENT # 브랜치의 배포 단계 (예: PRODUCTION)
      EnableAutoBuild: false # 커밋 시 자동 빌드 활성화 여부
      # EnvironmentVariables: # 브랜치에 적용되는 환경 변수
        # - Name: API_URL # 환경 변수 이름
        #   Value: https://api.example.com # 환경 변수 값
      Framework: React # 사용 프레임워크
      EnablePerformanceMode: false # 성능 모드 활성화 여부

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
  
  S3VPCEndpoint: # VPC 내부에서 S3에 프라이빗으로 접근 / 보완 필요 : EndpointType 명시, Policy 명시(접근 제어, 필요시)
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref TopycareVPC
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      RouteTableIds:
        - !Ref TopycareRouteTable
      VpcEndpointType: Gateway

  FoodHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: topycare-food-handler
      CodeUri: api/food-handler
      Handler: index.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs22.x
      Timeout: 60
      Architectures:
        - !Ref LambdaArchitecture
      VpcConfig:
        SecurityGroupIds:
          - !Ref TopycareSecurityGroup
        SubnetIds:
          - !Ref TopycareSubnet

  FoodHandlerApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref FoodHandlerApiName

  FoodHandlerApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FoodHandler.Arn}/invocations
      ResourceId: !GetAtt
        - FoodHandlerApi
        - RootResourceId
      RestApiId: !Ref FoodHandlerApi

  FoodHandlerDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - FoodHandlerApiMethod
    Properties:
      RestApiId: !Ref FoodHandlerApi
      StageName: call

  FoodHandlerApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt FoodHandler.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FoodHandlerApi}/call/GET/

  FoodHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${FoodHandler}
      RetentionInDays: 90

# serverless function 하기전에 vpc 구현하자.
# 보안과, 내부 리소스 간 통신 성능/안정성을 높이고, 불필요한 인터넷 요금 발생을 막기 위해서.

## 25.09.10. Todo
# VPC 내부에 Lambda를 배치하고, API Gateway와 Lambda를 통합하면
# Amplify 앱에서 API Gateway 엔드포인트로 요청을 보내고,
# API Gateway가 VPC 내부의 Lambda를 호출하여
# 암호화된 HTTPS(SSL/TLS)로 Amplify ↔ API Gateway ↔ Lambda 간 안전한 데이터 송수신이 가능합니다.