AWSTemplateFormatVersion: '2010-09-09'
Description: JD album bucket configuration
Parameters:
  BucketName:
    Type: String

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  User: # 버킷 접근 user 권한
    Type: AWS::IAM::User
    Properties:
      Path: /
      Policies:
        - PolicyName: AmazonS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub arn:${AWS::Partition}:s3:::${BucketName}
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:PutObject
                Resource:
                  - !Sub arn:${AWS::Partition}:s3:::${BucketName}/*

  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: User

  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name:
        Ref: AccessKey
      Description:
        Ref: User
      SecretString:
        Fn::GetAtt:
          - AccessKey
          - SecretAccessKey

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
