AWSTemplateFormatVersion: '2010-09-09'
Description: JD album api configuration
Parameters:
  BucketName:
    Type: String
  LambdaArchitecture:
    Description: The instruction set architecture for the function
    Type: String
    Default: arm64
    AllowedValues:
      - X86_64
      - arm64
  GetImageApiName:
    Description: Name of RestApi - GET image
    Type: String
  PostImageApiName:
    Description: Name of RestApi - POST image
    Type: String
  HostUrl:
    Description: domain when using other domain for cors.
    Type: String
    Default: http://localhost:3000

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  Role: # 람다 권한
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub lambda.${AWS::URLSuffix}
            Action: sts:AssumeRole
      Path: /service-role/
      ManagedPolicyArns: # https://docs.aws.amazon.com/lambda/latest/dg/security-iam-awsmanpol.html
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: AmazonS3Access # https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_s3_rw-bucket.html
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub arn:${AWS::Partition}:s3:::${BucketName}
                  - !Sub arn:${AWS::Partition}:s3:::${BucketName}/*
        - PolicyName: AWSAPIGatewayPushToCloudWatchLogs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                  - logs:GetLogEvents
                  - logs:FilterLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*"

  GetImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: GET Image router
      CodeUri: get-image
      Handler: index.handler
      Role: !GetAtt Role.Arn
      Runtime: nodejs20.x
      Timeout: 180
      Architectures:
        - !Ref LambdaArchitecture
      Environment:
        Variables:
          SOURCE_BUCKET: !Ref BucketName
          HOST_URL: !Ref HostUrl

  GetImageApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref GetImageApiName

  GetImageApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetImageFunction.Arn}/invocations
      ResourceId: !GetAtt
        - GetImageApi
        - RootResourceId
      RestApiId: !Ref GetImageApi

  GetImageDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - GetImageApiMethod
    Properties:
      RestApiId: !Ref GetImageApi
      StageName: call

  GetImageApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt GetImageFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${GetImageApi}/call/GET/

  GetImageFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetImageFunction}
      RetentionInDays: 90

  # PostImageFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: post-image
  #     Description: POST Image router
  #     Handler: index.handler
  #     Role: !GetAtt Role.Arn
  #     Runtime: nodejs20.x
  #     Timeout: 180
  #     Architectures:
  #       - !Ref LambdaArchitecture
  #     Environment:
  #       Variables:
  #         SOURCE_BUCKET: !Ref BucketName

  # PostImageApi:
  #   Type: AWS::ApiGateway::RestApi
  #   Properties:
  #     Name: !Ref PostImageApiName

  # PostImageApiMethod:
  #   Type: AWS::ApiGateway::Method
  #   Properties:
  #     AuthorizationType: NONE
  #     HttpMethod: POST
  #     Integration:
  #       IntegrationHttpMethod: POST
  #       Type: AWS_PROXY
  #       Uri: !Sub >-
  #         arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PostImageFunction.Arn}/invocations
  #     ResourceId: !GetAtt PostImageApi.RootResourceId
  #     RestApiId: !Ref PostImageApi

  # PostImageDeployment:
  #   Type: AWS::ApiGateway::Deployment
  #   DependsOn:
  #     - PostImageApiMethod
  #   Properties:
  #     RestApiId: !Ref PostImageApi
  #     StageName: call

  # PostImageFunctionLogGroup:
  #   Type: AWS::Logs::LogGroup
  #   Properties:
  #     LogGroupName: !Sub /aws/lambda/${PostImageFunction}
  #     RetentionInDays: 90
